[project]
name = "api"
version = "0.1.0"
description = "API routes and mappings"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.109.0",
    "uvicorn[standard]>=0.27.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "httpx>=0.27.0",
    "watchfiles>=0.21.0",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = [
    "-q",
    "--no-header",
    "--tb=short",
    "--strict-markers",
    "-ra"
]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
log_cli = true
log_cli_level = "ERROR"
log_cli_format = "%(message)s"
console_output_style = "count"
markers = [
    "integration: marks integration tests",
    "unit: marks unit tests",
    "db: marks database tests"
]
