[project]
name = "app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "email-validator>=2.2.0",
    "faker>=33.1.0",
    "motor>=3.6.0",
    "pydantic>=2.10.3",
    "python-dotenv>=1.0.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.4",
    "pytest-asyncio>=0.24.0",
    "testcontainers>=3.7.1",
    "testcontainers-mongodb>=0.0.1rc1",
]

[tool.pytest.ini_options]
pythonpath = ["src"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = [
    "-q",
    "--no-header",
    "--tb=short",
    "--strict-markers",
    "-ra"
]
python_files = "test_*.py"
python_classes = "Test*"
python_functions = "test_*"
log_cli = true
log_cli_level = "ERROR"
log_cli_format = "%(message)s"
console_output_style = "count"
markers = [
    "integration: marks integration tests",
    "unit: marks unit tests",
    "db: marks database tests"
]

[tool.ruff.lint]
select = ["E", "F", "W", "C", "N", "B", "I"]
