name: Test Suite

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

# This ensures we don't have multiple workflows running for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1
  PIP_USE_UV: 1
  # Configure pytest to generate the XML report in a known location
  PYTEST_ADDOPTS: "--junitxml=test-results/junit.xml --log-file=test-results/pytest.log"

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    permissions:
      # These permissions are needed for dorny/test-reporter to create check runs
      checks: write
      pull-requests: write

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Create and activate virtual environment
        run: |
          python_path=$(which python)
          echo "Using Python from: $python_path"
          python -m venv .venv
          echo "VIRTUAL_ENV=${{ github.workspace }}/.venv" >> $GITHUB_ENV
          echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

          echo "Python version:"
          python --version
          echo "Python path:"
          which python

      - name: Setup development environment
        run: python -m scripts.setup

      # Create the results directory before running tests
      - name: Prepare test environment
        run: mkdir -p test-results

      - name: Run tests
        run: python -m scripts.test
        # Continue to the reporting step even if tests fail
        continue-on-error: true

      # This will create a nice report in the PR
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure() # run this step even if previous step failed
        with:
          name: Test Results
          path: test-results/junit.xml
          reporter: jest-junit # Format of test results
          fail-on-error: true

      # We still keep the artifact upload for detailed logs
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: test-results/
          retention-days: 30
