name: Test Suite

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 1
  PIP_USE_UV: 1

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
        # Add Python 3.13 as an experimental build that's allowed to fail
        include:
          - os: ubuntu-latest
            python-version: "3.13"
            experimental: true

    continue-on-error: ${{ matrix.experimental || false }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: "latest"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Allow alpha/beta/rc releases for Python 3.13
          allow-prereleases: ${{ matrix.experimental || false }}

      - name: Create virtual environment
        run: |
          # Ensure we're using the correct Python version
          python --version
          # Create virtual environment with explicit Python path
          uv venv --python $(which python)
          echo "${{ github.workspace }}/.venv/bin" >> $GITHUB_PATH

      - name: Setup development environment
        run: python -m scripts.setup

      - name: Run tests
        run: python -m scripts.test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.python-version }}
          path: |
            test-results.xml
            pytest.log
          retention-days: 30
